apiVersion: v1
kind: Pod
metadata:
  name: influxdb
  namespace: ricplt
  labels:
    app: influxdb
spec:
  containers:
  - name: influxdb
    image: influxdb:1.8-alpine
    imagePullPolicy: Never
    ports:
      - containerPort: 8086
    envFrom:
      - configMapRef:
          name: configuration-env
    volumeMounts:
      - name: influxdb-data
        mountPath: /var/lib/influxdb
  volumes:
    - name: influxdb-data
      persistentVolumeClaim:
        claimName: influxdb-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: grafana
  namespace: ricplt
  labels:
    app: grafana
spec:
  initContainers:
  - name: fix-permissions
    image: busybox
    command: ["sh", "-c", "chown -R 472:472 /var/lib/grafana"]
    volumeMounts:
    - name: grafana-data
      mountPath: /var/lib/grafana

  containers:
  - name: grafana
    image: grafana/grafana:8.0.2
    imagePullPolicy: Never
    ports:
      - containerPort: 3000
    envFrom:
      - configMapRef:
          name: configuration-env
    volumeMounts:
      - name: grafana-data
        mountPath: /var/lib/grafana
      - name: grafana-dashboards
        mountPath: /var/lib/grafana/dashboards
      - name: grafana-provisioning
        mountPath: /etc/grafana/provisioning/dashboards/all.yml
        subPath: all.yml
      - name: grafana-provisioning
        mountPath: /etc/grafana/provisioning/datasources/influxdb.yml
        subPath: influxdb.yml
  volumes:
    - name: grafana-data
      persistentVolumeClaim:
        claimName: grafana-pvc
    - name: grafana-dashboards
      configMap:
        name: grafana-dashboards
    - name: grafana-provisioning
      configMap:
        name: grafana-provisioning
---
apiVersion: v1
kind: Pod
metadata:
  name: telegraf
  namespace: ricplt
  labels:
    app: telegraf
spec:
  containers:
  - name: telegraf
    image: telegraf:1.18-alpine
    imagePullPolicy: Never
    ports:
      - containerPort: 8125
        protocol: UDP
    volumeMounts:
      - name: telegraf-config
        mountPath: /etc/telegraf/telegraf.conf
        subPath: telegraf.conf
  volumes:
    - name: telegraf-config
      configMap:
        name: telegraf-config
---
apiVersion: v1
kind: Pod
metadata:
  name: ns-3
  namespace: ricplt
spec:
  dnsPolicy: ClusterFirst
  containers:
  - name: ns3
    image: ns3:v1
    imagePullPolicy: Never
    command: ["sleep", "infinity"]
