{
 "title": "NS3 Neighbor Metrics Monitoring",
 "time": { "from": "2025-08-13T12:17:44.191Z", "to": "2025-08-13T12:17:44.998Z" },
 "panels": [
  {
   "title": "Neighbor SINR 1 ( per UE )",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "UE $tag_ueImsiComplete $col",
     "query": "SELECT \"l3_neigh_sinr_1\" AS \"SINR \", \"l3_neigh_id_1_cellid\" AS \"Cell ID\"\nFROM \"cu_cp_bucket\"\nWHERE $timeFilter\nGROUP BY \"ueImsiComplete\""
    }
   ]
  },
  {
   "title": "Neighbor SINR 2 ( per UE )",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "UE $tag_ueImsiComplete $col",
     "query": "SELECT \"l3_neigh_sinr_2\" AS \"SINR \", \"l3_neigh_id_2_cellid\" AS \"Cell ID\"\nFROM \"cu_cp_bucket\"\nWHERE $timeFilter\nGROUP BY \"ueImsiComplete\""
    }
   ]
  },
  {
   "title": "Neighbor SINR 3 ( per UE )",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "UE $tag_ueImsiComplete $col",
     "query": "SELECT \"l3_neigh_sinr_3\" AS \"SINR \", \"l3_neigh_id_3_cellid\" AS \"Cell ID\"\nFROM \"cu_cp_bucket\"\nWHERE $timeFilter\nGROUP BY \"ueImsiComplete\""
    }
   ]
  },
  {
   "title": "DRB UE THP ( per UE )",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "SELECT \"drb_uethp_dl_ueid\" FROM \"du_bucket\" WHERE $timeFilter GROUP BY \"ueImsiComplete\""
    }
   ]
  }
 ]
}