{
 "title": "NS3 Metrics Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Serving SINR ( per UE )",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"l3_serving_sinr\" FROM \"cu_cp_bucket\" WHERE $timeFilter GROUP BY \"ueImsiComplete\""
    }
   ]
  },
  {
   "title": "Serving Cell ID ( per UE )",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "SELECT \"l3_serving_id_m_cellid\" FROM \"cu_cp_bucket\" WHERE $timeFilter GROUP BY \"ueImsiComplete\""
    }
   ]
  },
  {
   "title": "Number of Active UE ( per Cell ID )",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "SELECT \"num_active_ues\" FROM \"cu_cp_bucket\" WHERE $timeFilter GROUP BY \"L3ServingId\""
    }
   ]
  },
  {
   "title": "Error Rate ( per UE )",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "SELECT \"tb_err_total_nbr_dl_1\" FROM \"du_bucket\" WHERE $timeFilter GROUP BY \"ueImsiComplete\""
    }
   ]
  },
  {
   "title": "PRB Usage ( per Cell ID )",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "SELECT \"rru_prb_used_dl\" FROM \"du_bucket\" WHERE $timeFilter GROUP BY \"nrCellId\""
    }
   ]
  }
 ]
}