{
 "title": "UE - Cell SINR",
 "time": { "from": "2025-07-20T12:55:07.291Z", "to": "2025-07-20T12:55:08.327Z" },
 "panels": [
  {
   "title": "UE #1 Cells SINR",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT cell_2_sinr, cell_3_sinr, cell_4_sinr, cell_5_sinr, cell_6_sinr, cell_7_sinr \nFROM ue_cell_bucket \nWHERE ue_imsi_complete = 00001"
    }
   ]
  },
  {
   "title": "UE #2 Cells SINR",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT cell_2_sinr, cell_3_sinr, cell_4_sinr, cell_5_sinr, cell_6_sinr, cell_7_sinr \nFROM ue_cell_bucket \nWHERE ue_imsi_complete = 00002"
    }
   ]
  },
  {
   "title": "UE #3 Cells SINR",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT cell_2_sinr, cell_3_sinr, cell_4_sinr, cell_5_sinr, cell_6_sinr, cell_7_sinr \nFROM ue_cell_bucket \nWHERE ue_imsi_complete = 00003"
    }
   ]
  },
  {
   "title": "UE #22 Cells SINR",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT cell_2_sinr, cell_3_sinr, cell_4_sinr, cell_5_sinr, cell_6_sinr, cell_7_sinr \nFROM ue_cell_bucket \nWHERE ue_imsi_complete = 00022"
    }
   ]
  },
  {
   "title": "UE #23 Cells SINR",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT cell_2_sinr, cell_3_sinr, cell_4_sinr, cell_5_sinr, cell_6_sinr, cell_7_sinr \nFROM ue_cell_bucket \nWHERE ue_imsi_complete = 00023"
    }
   ]
  },
  {
   "title": "UE #24 Cells SINR",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT cell_2_sinr, cell_3_sinr, cell_4_sinr, cell_5_sinr, cell_6_sinr, cell_7_sinr \nFROM ue_cell_bucket \nWHERE ue_imsi_complete = 00024"
    }
   ]
  }
 ]
}